#!/bin/sh

ROOT="./root"
LIB="$ROOT/usr/local/lib"
BIN="$ROOT/usr/local/bin"
SRC="../neko/bin"

function checkForError() {
    if [ $? != 0 ]; then
        echo "-- Error on $1"
        exit $?
    else
        echo "++ Success on $1"    
    fi    
}

if [ -d "$ROOT" ]; then	
	sudo rm -R *.pkg
	sudo rm *.zip
	sudo rm -R $ROOT	
fi

mkdir -p $BIN
checkForError "creating $BIN folder"
mkdir -p $LIB
checkForError "creating $LIB folder"

cp $SRC/*.dylib $LIB
checkForError "copying .dylibs"
cp $SRC/*.ndll $LIB
checkForError "copying .ndlls"
cp $SRC/neko* $BIN
checkForError "copying binaries"

sudo chown -R root:admin root
checkForError "setting owner on root"
sudo chmod -R o=rx,g=rwx,u=rxw root
checkForError "setting rights on root"

ISF="$ROOT/Install_resources"
mkdir $ISF
checkForError "creating $ISF folder"
cp postflight $ISF/
checkForError "copying postflight script"

sudo /Developer/Tools/packagemaker -build -proj neko.pmproj -p neko.pkg -v
checkForError "creating package"