#!/bin/sh

ROOT="./root"
LIB="$ROOT/usr/local/lib"
BIN="$ROOT/usr/local/bin"
SRC="../neko/bin"

if [ -d "$ROOT" ]; then 
	echo "removing previous builds"
	sudo rm -R *.pkg
	sudo rm *.zip
	sudo rm -R $ROOT
fi

echo "creating root folders"
mkdir -p $BIN
mkdir -p $LIB

echo "copying source files"
cp $SRC/*.dylib $LIB
cp $SRC/*.ndll $LIB
cp $SRC/neko* $BIN

echo "setting rights on copied files"
sudo chown -R root:admin root
sudo chmod -R o=rx,g=rwx,u=rxw root

echo "copying installer script"
ISF="$ROOT/Install_resources"
mkdir $ISF
cp postflight $ISF/

echo "running PackageMaker"
echo ""
sudo /Developer/Tools/packagemaker -build -proj neko.pmproj -p neko.pkg -v

echo ""
echo "done"
